/**:    # note that this affects ALL nodes!
  ros__parameters:
  ## state manager
    state_source:         "mocap"           # 'apm', 'tf-mocap', 'mocap'
    tf_rate:              100
    tf_buffer_time:       2                 # seconds
    tf_myframe:           "agent-1"
    tf_baseframe:         "map"
    filter_type:          "median"          # 'gauss' 'median' 'lwma' 'kalman' 'savit-gol'
    filter_length:        21                # has no effect if filter_type=='kalman'
    kf_params:            [0.001, 5.0]      # [meas.cov, proc.cov]
    mocap_topic:          "/mocap/a1/a1"    # used if state-source=mocap
    use_rtkbaseframe:     false
    rtkbase_offset_type:  "base"            # 'base' or 'custom', used only if use_rtkbaseframe==true
    use_zvel_from_ap:     true              # (outdoors) use autopilot's reported zvel or calc ourselves
  ## lqg control
    controller_type:      "pos-vel"         # pos-vel, vel-only, open-loop
    total_mass:           0.85              # total in-air
    controller_rate:      50
    bias_compensation:    "auto"            # 'always-{on/off}', 'auto'; controls running the estimator 
    apply_est_biases:     false             # apply corrections from bias estimator
    apply_extf_corr:      false             # correct for provided external forces
    enable_flatness_ff:   false             # use accel-space flatness
    flatness_ff_factor:   1.0               # used only if flatness is enabled
    use_stricter_gains:   false             # precomputed (slightly more) aggressive 
    mass_estimation:      true              # estimate approx mass
    mass_correction:      false             # apply estimated mass (discouraged)
    refstate_accels_mode: "ignore"          # (robomaster) 'limits', 'feedforward'; controls accels use
    accel_ff_factor:      0.25              # (robomaster) scale refstate accels for feedfwd
    chassis_length:       0.4               # (robomaster)
    chassis_width:        0.3               # (robomaster)
    wheel_radius:         0.10              # (robomaster)
    estimator_rate:       10
    estimator_coeffs:     [0.1, 0.2, 0.8, 0.2, 0.3]
    estimator_use_cmdacc: false
  ## waypoint manager
    init_NEDy:            [0.0]             # setting this to a 4-vec will trigger init wpt
  ## apm handler
    thrust_scaler:        200               # scales thrust down
    use_thrust_calib:     false             # use a calib poly eqn.
  ## flight mode arbitrator
    takeoff_land_spd:     0.2               # m/s, speed not velocity
    init_hover_pd:        -0.75             # hover here at first takeoff
    arm_takeoff_delay:    4.0               # wait this long to takeoff after arming
    mission_wdg_timeout:  1.0               # switch to auto-hover if no target for a while 
    hover_wdg_timeout:    -1.0              # land if auto-hover for a while (disable=-1)
    await_cmd_after_rc:   true              # wait for arm-service call even if pilot okays
    sys_ready_checks:     3                 # bitfield: 0b[x x x x x rtk, cstate, connected]
    use_ap_landing:       false             # use autopilot's land function (use outdoors)
    