# mavros_param.yaml
/**:
  ros__parameters: 
    plugin_denylist: ["*"]
    plugin_allowlist: ["sys_status", "command", "setpoint_raw", "global_position", "rc_io"]
    fcu_url: /dev/ttyAMA0:921600

/**:
  ros__parameters:
    thrust_scaling: 1.0
mavros_router:
  ros__parameters: {}

